apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rgunasekaran-github/aks-devops-gitops.git
    targetRevision: main
    path: external-secrets-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
